### ISSUE TITLE
Can we not create a single build command for both Go and UI?

### ISSUE THREAD

**Issue by gvsvarun** [KingAkeem/goTor#12]
Instead of using just Webpack, why not configure the build command for both GO and UI.

Somehow also pass an argument to make sure liver server also runs only for dev only and not for everyone?

**Comment by KingAkeem** [comment]
That doesn't sound like a bad idea and would simplify the build process, this project has been moved to [this repo](https://github.com/KingAkeem/TorBotApp). Do you think you could come up with a proposal for the idea?

**Comment by gvsvarun** [comment]
Sure. I will see what I can do.
