### ISSUE TITLE
Implement getemails from TorBot

### ISSUE THREAD

**Issue by KingAkeem** [KingAkeem/gotor#6]
Here's a link for reference and I'm open to any questions. 
https://github.com/DedSecInside/TorBot/blob/dev/modules/getemails.py

**Comment by sheoran27** [comment]
Any contribution still required?

**Comment by KingAkeem** [comment]
I've basically deserted the project but if you'd like to contribute then that'd be fine.

**Comment by KingAkeem** [comment]
Working on it again
