### ISSUE TITLE
Implement getHeaders function from info.py in TorBot

### ISSUE THREAD

**Issue by KingAkeem** [KingAkeem/goTor#7]
The only part of info.py that we're concerned about is the `getHeaders` function https://github.com/DedSecInside/TorBot/blob/a829cc17c9a3aee5596b39e17d3e37b9923d24ea/modules/info.py#L35

**Comment by yulrizka** [comment]
Hello, this seems to be an interesting, I would like to take a shot on it :)

**Comment by atlking** [comment]
This project has actually been moved here: https://github.com/KingAkeem/TorBotApp. I would appreciate any help though, I'd like to move our framework from React to Vue and finetune the UI to be more user-friendly. Testing and documentation would also be very helpful.

**Comment by KingAkeem** [comment]
This project has actually been moved here: https://github.com/KingAkeem/TorBotApp. I would appreciate any help though, I'd like to move our framework from React to Vue and finetune the UI to be more user-friendly. Testing and documentation would also be very helpful.
